export const GET_QUESTION_LIST_REQUEST = "GET_QUESTION_LIST_REQUEST";
export const GET_QUESTION_LIST_SUCCESS = "GET_QUESTION_LIST_SUCCESS";
export const GET_QUESTION_LIST_FAIL = "GET_QUESTION_LIST_FAIL";